### ISSUE TITLE
Undefined method fullname for null

### ISSUE THREAD

**Issue by bhernez** [paddle8/ember-locales#1]
In ember-locales/app/initializers/i18n.js file, around line 32, the argument 'module' is received as null, so the assertion doesn't run and the code fails to continue. I'm not sure why the argument is receive in that way, but this is a just a patch to prevent it.

```
locales.forEach(function (module) {
      if(module){
          Ember.assert(`${module.fullName} must export a translation table.`, module.contents != null);
          var table = module.contents.default;
          translations[module.name] = table;
      }
    });
```

**Comment by tim-evans** [comment]
Closed. I'm choosing not to support this addon, but will accept patches for the time being. There seems to be a proper solution shaking out over at https://github.com/yahoo/ember-intl/issues/109.

I will try to write something for ember-watson to convert translations over to whatever is the solution.
